# -*- coding: utf-8 -*-
"""Hugging face speech to text

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_LutY5f20AT4mWt0vmmNaUGC-C2RTwR
"""



pip install transformers

from transformers import pipeline

import transformers
print(transformers.__version__)

import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import numpy as np

tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

audio, sampling_rate = librosa.load('/sample-audio.wav', sr = 16000)

audio, sampling_rate

display.Audio('/sample-audio.wav', autoplay = True)

input_values = tokenizer(audio, return_tensors = 'pt').input_values
input_values

logits = model(input_values).logits
logits

predicted_ids = torch.argmax(logits, dim = -1)

transcriptions = tokenizer.decode(predicted_ids[0])

transcriptions