# -*- coding: utf-8 -*-
"""text generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jrw27rlXKX5_QUf-vpBtloW1K0YWU1LG
"""

#text generation
import pandas as pd
from transformers import pipeline

poems = pd.read_csv('robert_frost_collection.csv')
poems.head()

content = poems["Content"].dropna().tolist()

lines = []
for poem in content:
  for line in poem.split("\n"):
    lines.append(line.rstrip())

lines = [line for line in lines if len(line)> 0]
lines[:5]

gen = pipeline("text-generation")

lines[0]

gen(lines[0],max_length = 20)

gen(lines[1], max_length = 30, num_return_sequences = 2)

import textwrap
def wrap(x):
  return textwrap.fill(x, replace_whitespace = False, fix_sentence_endings= True)

out = gen(lines[0], max_length = 30)
print(wrap(out[0]['generated_text']))

prompt = "transformers have a wide varient of applications in nlp"
out = gen(prompt, max_length = 100)
print(wrap(out[0]['generated_text']))

prompt = "Introducing to myself into the world of mine where I will teach, give my opinion and listen to my fellows"
out = gen(prompt, max_length = 100)
print(wrap(out[0]['generated_text']))